"""add subscriptions, payments, workflows, apis, executions

Revision ID: 06a4497af772
Revises: 8098b3cf7d17
Create Date: 2026-07-06 02:44:07.741122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06a4497af772'
down_revision: Union[str, Sequence[str], None] = '8098b3cf7d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # matched_transaction_id -> payment_transactions.id is added below via a
    # separate create_foreign_key call: payment_transactions doesn't exist yet
    # here, and the two tables reference each other (mutual matching, §9.3).
    op.create_table('bkash_sms_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('sms_sender', sa.String(length=40), nullable=True),
    sa.Column('dedupe_hash', sa.String(length=64), nullable=False),
    sa.Column('parsed_trx_id', sa.String(length=40), nullable=True),
    sa.Column('parsed_amount_bdt', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('parsed_sender_msisdn', sa.String(length=20), nullable=True),
    sa.Column('matched_transaction_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_hash')
    )
    op.create_index(op.f('ix_bkash_sms_receipts_matched_transaction_id'), 'bkash_sms_receipts', ['matched_transaction_id'], unique=False)
    op.create_index(op.f('ix_bkash_sms_receipts_parsed_trx_id'), 'bkash_sms_receipts', ['parsed_trx_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Enum('subscription', 'api_access', name='paymentpurpose', native_enum=False, length=32), nullable=False),
    sa.Column('plan_tier', sa.Enum('free', 'pro', 'max', name='plantier', native_enum=False, length=32), nullable=True),
    sa.Column('api_id', sa.UUID(), nullable=True),
    sa.Column('amount_expected_bdt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_received_bdt', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bkash_trx_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('pending', 'submitted', 'verified', 'rejected', 'expired', name='paymentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('matched_sms_id', sa.UUID(), nullable=True),
    sa.Column('verification_method', sa.Enum('auto_sms', 'manual_admin', name='verificationmethod', native_enum=False, length=32), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_user_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # api_id -> custom_apis.id is added later via create_foreign_key: custom_apis
    # doesn't exist yet at this point in the migration.
    sa.ForeignKeyConstraint(['matched_sms_id'], ['bkash_sms_receipts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_bkash_trx_id'), 'payment_transactions', ['bkash_trx_id'], unique=True)
    op.create_index(op.f('ix_payment_transactions_status'), 'payment_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_payment_transactions_user_id'), 'payment_transactions', ['user_id'], unique=False)
    op.create_foreign_key('fk_bkash_sms_receipts_matched_transaction_id', 'bkash_sms_receipts',
                           'payment_transactions', ['matched_transaction_id'], ['id'], ondelete='SET NULL')
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('free', 'pro', 'max', name='plantier', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'cancelled', name='subscriptionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_transaction_id'], ['payment_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_expires_at'), 'subscriptions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_index('uq_one_active_sub_per_user', 'subscriptions', ['user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_url', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('recording', 'draft', 'ready', 'archived', name='workflowstatus', native_enum=False, length=32), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('extraction', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sample_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('browser_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('auth_state_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_user_id'), 'workflows', ['user_id'], unique=False)
    op.create_table('custom_apis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'shared', name='apivisibility', native_enum=False, length=32), nullable=False),
    sa.Column('price_bdt', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('workflow_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('openapi_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spec_status', sa.Enum('pending', 'generating', 'ready', 'failed', name='specstatus', native_enum=False, length=32), nullable=False),
    sa.Column('cache_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_apis_owner_id'), 'custom_apis', ['owner_id'], unique=False)
    op.create_index(op.f('ix_custom_apis_slug'), 'custom_apis', ['slug'], unique=True)
    op.create_index(op.f('ix_custom_apis_workflow_id'), 'custom_apis', ['workflow_id'], unique=False)
    op.create_foreign_key('fk_payment_transactions_api_id', 'payment_transactions',
                           'custom_apis', ['api_id'], ['id'], ondelete='SET NULL')
    op.create_table('api_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_id', sa.UUID(), nullable=False),
    sa.Column('caller_user_id', sa.UUID(), nullable=True),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'timeout', name='executionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_truncated', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('failure_artifact_path', sa.Text(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['custom_apis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['caller_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exec_api_created', 'api_executions', ['api_id', 'created_at'], unique=False)
    op.create_table('api_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['custom_apis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_invites_api_id'), 'api_invites', ['api_id'], unique=False)
    op.create_index(op.f('ix_api_invites_token'), 'api_invites', ['token'], unique=True)
    op.create_table('api_access_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('granted_via', sa.Enum('invite', 'purchase', 'admin', name='grantsource', native_enum=False, length=32), nullable=False),
    sa.Column('invite_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['custom_apis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invite_id'], ['api_invites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id', 'user_id', name='uq_grant_api_user')
    )
    op.create_index(op.f('ix_api_access_grants_api_id'), 'api_access_grants', ['api_id'], unique=False)
    op.create_index(op.f('ix_api_access_grants_user_id'), 'api_access_grants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_access_grants_user_id'), table_name='api_access_grants')
    op.drop_index(op.f('ix_api_access_grants_api_id'), table_name='api_access_grants')
    op.drop_table('api_access_grants')
    op.drop_index(op.f('ix_api_invites_token'), table_name='api_invites')
    op.drop_index(op.f('ix_api_invites_api_id'), table_name='api_invites')
    op.drop_table('api_invites')
    op.drop_index('ix_exec_api_created', table_name='api_executions')
    op.drop_table('api_executions')
    op.drop_index(op.f('ix_custom_apis_workflow_id'), table_name='custom_apis')
    op.drop_index(op.f('ix_custom_apis_slug'), table_name='custom_apis')
    op.drop_index(op.f('ix_custom_apis_owner_id'), table_name='custom_apis')
    op.drop_constraint('fk_payment_transactions_api_id', 'payment_transactions', type_='foreignkey')
    op.drop_table('custom_apis')
    op.drop_index(op.f('ix_workflows_user_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index('uq_one_active_sub_per_user', table_name='subscriptions', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_expires_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_payment_transactions_user_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_bkash_trx_id'), table_name='payment_transactions')
    op.drop_constraint('fk_bkash_sms_receipts_matched_transaction_id', 'bkash_sms_receipts', type_='foreignkey')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_bkash_sms_receipts_parsed_trx_id'), table_name='bkash_sms_receipts')
    op.drop_index(op.f('ix_bkash_sms_receipts_matched_transaction_id'), table_name='bkash_sms_receipts')
    op.drop_table('bkash_sms_receipts')
    # ### end Alembic commands ###
