"""add api allowed emails table

Revision ID: 5b9817751bb1
Revises: 0c443386726a
Create Date: 2026-07-07 23:54:29.188316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b9817751bb1'
down_revision: Union[str, Sequence[str], None] = '0c443386726a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_allowed_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['api_id'], ['custom_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_id', 'email', name='uq_allowed_email_api')
    )
    op.create_index(op.f('ix_api_allowed_emails_api_id'), 'api_allowed_emails', ['api_id'], unique=False)
    op.create_index(op.f('ix_api_allowed_emails_email'), 'api_allowed_emails', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_allowed_emails_email'), table_name='api_allowed_emails')
    op.drop_index(op.f('ix_api_allowed_emails_api_id'), table_name='api_allowed_emails')
    op.drop_table('api_allowed_emails')
    # ### end Alembic commands ###
