"""add plan_settings table

Revision ID: 8c395fe24b36
Revises: c485bcb5502c
Create Date: 2026-07-06 23:52:41.476268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.config import settings


# revision identifiers, used by Alembic.
revision: str = '8c395fe24b36'
down_revision: Union[str, Sequence[str], None] = 'c485bcb5502c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


plan_settings_table = sa.table(
    'plan_settings',
    sa.column('tier', sa.String),
    sa.column('price_bdt', sa.Integer),
    sa.column('daily_creation_limit', sa.Integer),
    sa.column('can_share', sa.Boolean),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_settings',
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('price_bdt', sa.Integer(), nullable=False),
    sa.Column('daily_creation_limit', sa.Integer(), nullable=True),
    sa.Column('can_share', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tier')
    )
    # ### end Alembic commands ###

    # Seed the three tiers from the current hardcoded/env defaults (env price
    # vars remain only as seed defaults from here on — runtime reads come from
    # this table, via app/services/plans.py).
    op.bulk_insert(
        plan_settings_table,
        [
            {"tier": "free", "price_bdt": 0, "daily_creation_limit": 5, "can_share": False},
            {"tier": "pro", "price_bdt": settings.plan_price_pro_bdt, "daily_creation_limit": 50, "can_share": True},
            {"tier": "max", "price_bdt": settings.plan_price_max_bdt, "daily_creation_limit": None, "can_share": True},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_settings')
    # ### end Alembic commands ###
