"""add accounts columns and rename admin role

Revision ID: c485bcb5502c
Revises: 06a4497af772
Create Date: 2026-07-06 22:38:33.025478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c485bcb5502c'
down_revision: Union[str, Sequence[str], None] = '06a4497af772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'google_sub',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###

    # Role rename: 'admin' -> 'super_admin' (role is a plain varchar, no CHECK
    # constraint to alter — see app/models/base.py::enum_column).
    op.execute("UPDATE users SET role = 'super_admin' WHERE role = 'admin'")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("UPDATE users SET role = 'admin' WHERE role = 'super_admin'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'google_sub',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('users', 'suspended_at')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
